// import '../src/styles/globals.css'
// // import { Inter } from 'next/font/google'

// // const inter = Inter({ subsets: ['latin'] })



// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
// "use client";
import { Roboto } from 'next/font/google'
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})
import "../src/styles/globals.css";
import { ReactNode } from "react";
import Navbar from "@/src/components/Navbar/Navbar";
import Provider from '@/src/components/Provider/Provider';
interface IProps {
  children: ReactNode;
}
export const metadata = {
  title: 'desi buck',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: IProps) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-[#f9f9f9]`}>
        <Provider>
          <Navbar/>
          {children}
        </Provider>
      </body>
    </html>
  );
}
